#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2016 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

MINIDLNA_CONFIG="/etc/minidlna.conf"
XPATH="/config/services/minidlna"

OMV_MINIDLNA_DB_DIR=${OMV_MINIDLNA_DB_DIR:-"/var/cache/minidlna"}
OMV_MINIDLNA_LOG_DIR=${OMV_MINIDLNA_LOG_DIR:-"/var/log"}

log_level=$(omv_config_get "${XPATH}/loglevel")
name=$(omv_config_get "${XPATH}/name")
port=$(omv_config_get "${XPATH}/port")
rootcontainer=$(omv_config_get "${XPATH}/rootcontainer")
strict=$(omv_config_get "${XPATH}/strict")
tivo=$(omv_config_get "${XPATH}/tivo")
extraoptions=$(omv_config_get "${XPATH}/extraoptions")

if [ -n "${rootcontainer}" ]; then
    rootcontainer="root_container=${rootcontainer}"
else
    rootcontainer="#root_container=."
fi

if [ "${strict}" = "1" ]; then
    strict="yes"
else
    strict="no"
fi

if [ "${tivo}" = "1" ]; then
    tivo="yes"
else
    tivo="no"
fi

# Create minidlna config file
cat <<EOF > ${MINIDLNA_CONFIG}
port=${port}
#network_interface=eth0
friendly_name=${name}
db_dir=${OMV_MINIDLNA_DB_DIR}
log_dir=${OMV_MINIDLNA_LOG_DIR}
album_art_names=Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt.jpg/albumart.jpg/Album.jpg/album.jpg/Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg
inotify=yes
enable_tivo=${tivo}
strict_dlna=${strict}
notify_interval=60
serial=31446138
model_number=1
${rootcontainer}
log_level=${log_level}
${extraoptions}
EOF


# Process FTP shares
index=$(omv_config_get_count "${XPATH}/shares/share")
while [ ${index} -gt 0 ]; do

    # Get the shared folder reference and path
    sfref=$(omv_config_get "${XPATH}/shares/share[position()=${index}]/sharedfolderref")
    sfpath=$(omv_get_sharedfolder_path "${sfref}")
    mtype=$(omv_config_get "${XPATH}/shares/share[position()=${index}]/mtype")

    if [ -n "${mtype}" ]; then
        mtype="${mtype},"
    fi

    if [ -n "${sfpath}" ]; then
        echo "media_dir=${mtype}${sfpath}" >> ${MINIDLNA_CONFIG}
    fi

    index=$(( ${index} - 1 ))
done
