#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2026 openmediavault plugin developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        if [ -z "${2}" ]; then
            deb-systemd-helper disable minidlna.service >/dev/null || true
            deb-systemd-invoke stop minidlna.service >/dev/null || true
        fi

        # Activate package triggers.
        dpkg-trigger update-workbench

        if ! grep -q 'OMV_MINIDLNA_SERIAL' /etc/default/openmediavault; then
            omv_set_default "OMV_MINIDLNA_SERIAL" "$((1000 + RANDOM % 9999))$((1000 + RANDOM % 9999))" false
            omv-salt stage run --quiet prepare
        fi

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.minidlna"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.minidlna" "${2}"
        fi

        omv-salt deploy run --quiet minidlna
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
