#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)

        SERVICE_XPATH_NAME="minidlna"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "name" "MiniDLNA Server on OpenMediaVault"
            omv_config_add_element "${SERVICE_XPATH}" "port" "8200"
            omv_config_add_element "${SERVICE_XPATH}" "strict" "0"
            omv_config_add_element "${SERVICE_XPATH}" "tivo" "0"
            omv_config_add_element "${SERVICE_XPATH}" "shares"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/loglevel"; then
            omv_config_add_element "${SERVICE_XPATH}" "loglevel" "error"
        fi

        echo "Add ${SERVICE_XPATH_NAME} user to group: users"
        usermod -G users ${SERVICE_XPATH_NAME}

        if grep -q "fs.inotify.max_user_watches" /etc/sysctl.conf; then
            echo "Increasing max user watches ..."
            echo "fs.inotify.max_user_watches=100000" >> /etc/sysctl.conf
            echo 100000 > /proc/sys/fs/inotify/max_user_watches
        fi

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
