#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

unset USER

DEFAULT=/etc/default/minidlna

# Get values from ${DEFAULT}, if it exists.
[ -r ${DEFAULT} ] && . ${DEFAULT}

# Set the default user and user.
if [ -z ${USER} ]; then
    USER=minidlna
fi
if [ -z ${GROUP} ]; then
    GROUP=minidlna
fi

CONFIG=/etc/minidlna.conf

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)

        ########################################################################
        #  Update the configuration.
        #   <config>
        #       <services>
        #           <minidlna>
        #               <enable>0</enable>
        #               <name>MiniDLNA Server on OpenMediaVault</name>
        #               <port>8200</port>
        #               <strict>0</strict>
        #               <tivo>0</tivo>
        #               <shares></shares>
        #           </minidlna>
        #       </services>
        #   </config>
        ########################################################################

        if ! omv_config_exists "/config/services/minidlna"; then
            echo "Initialize configuration"
            object="<enable>0</enable>"
            object="${object}<name>MiniDLNA Server on OpenMediaVault</name>"
            object="${object}<port>8200</port>"
            object="${object}<strict>8200</strict>"
            object="${object}<tivo>8200</tivo>"

            object="${object}<shares></shares>"
            omv_config_add_element "/config/services" "minidlna" "${object}" true
        fi

        echo "Add minidlna user to group: users"
        usermod -G users minidlna

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
